### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by memantine** [memantine/eemcs#15]
Implement roles package. Suggested roles/permissions might be:
- Admin
 - agenda_edit
 - agenda_view
 - company_edit
 - company_add
 - company_view
 - company_review <sup>[1](#needed)</sup>
 - student_edit
 - student_add
 - student_view
 - student_review  <sup>[1](#needed)</sup>
 - sms_mail
 - admin_priviliges
- Company
 - profile
 - preference_student
 - resume
- Student
 - profile
 - resume_upload
 - resume_checked
 - preference_company
---
Permissions for both company and student apply to what they should be able to see. A student for example should not be able to upload their resume if they have not completed their profile. In turn they should only gain access to preferences when they have completed both profile and resume and have their resume reviewed by admins.
Privileges for all groups might expand during development

<a name="needed">1</a>: Necessary, or covered by add/edit/view?

**Comment by danielkappelle** [comment]
Basic roles fixed
