### ISSUE TITLE
File upload check

### ISSUE THREAD

**Issue by ernebronk** [memantine/eemcs#32]
We need to filter the uploaded files for extention and size, i already made a start, see fscollection.js

**Comment by ernebronk** [comment]
Upload only PDF or images en remove from server when removed

**Comment by danielkappelle** [comment]
File check is fixed, has a neat error message too

**Comment by danielkappelle** [comment]
Fixed file remove for logos

**Comment by danielkappelle** [comment]
fixed file remove for cv's as well

**Comment by danielkappelle** [comment]
All done
