### ISSUE TITLE
Basic admin backend

### ISSUE THREAD

**Issue by danielkappelle** [memantine/eemcs#7]
Moet in:
- accounts aanmaken voor bedrijven
- zien wat zij hebben ingevuld

**Comment by danielkappelle** [comment]
added admin user in fixtures. also started working on admin panel

**Comment by danielkappelle** [comment]
fyi, it's in the roles_test branch

**Comment by memantine** [comment]
#15 & #16

**Comment by danielkappelle** [comment]
Have to make the admin panel only accessible for admin.. :p

**Comment by danielkappelle** [comment]
Geen user aanmaken als company, maar alleen de company aanmaken met potentieel meer users
